# Generated by Django 4.1.2 on 2022-10-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partie',
            name='FEN',
            field=models.TextField(blank=True),
        ),
    ]
