# Generated by Django 4.1.2 on 2022-10-08 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chessapp', '0009_remove_partie_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partie',
            name='user',
            field=models.ForeignKey(db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
